# Generated by Django 5.2.3 on 2025-06-19 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(help_text="Résumé de l'intervention")),
                ('actions_menees', models.TextField(help_text='Détails des actions techniques effectuées')),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='support.ticket')),
            ],
        ),
    ]
