# Generated by Django 5.2.3 on 2025-06-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technicien', 'Technicien'), ('supérieur', 'Supérieur')], default='technicien', max_length=20),
        ),
    ]
