# Generated by Django 5.2.3 on 2025-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_attente_confirmation', 'En attente de confirmation'), ('cloturé', 'Clôturé')], default='En attente', max_length=50),
        ),
    ]
