# Generated by Django 5.2.3 on 2025-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_ticket_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('En_attente_confirmation', 'En attente de confirmation'), ('cloturé', 'Clôturé')], default='En attente', max_length=50),
        ),
    ]
