# Generated by Django 5.2.3 on 2025-06-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_ticket_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_attente_confirmation', 'En attente de confirmation'), ('cloture', 'Clôturé')], default='En attente', max_length=50),
        ),
    ]
