# Generated by Django 5.2.3 on 2025-06-25 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_alter_ticket_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscaladeHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('superieur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalades_reçues', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalades', to='support.ticket')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalades_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
