# Generated by Django 5.2.3 on 2025-06-25 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_escaladehistorique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaladehistorique',
            name='superieur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalades_recues', to=settings.AUTH_USER_MODEL),
        ),
    ]
