# Generated by Django 5.2.3 on 2025-06-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_escaladehistorique_superieur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalade_vers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_escalades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='niveau_escalade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='actions_menees',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='resume',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_attente_confirmation', 'En attente de confirmation'), ('cloture', 'Clôturé')], default='en_attente', max_length=50),
        ),
    ]
